export default interface Config {
    id: null,
    nome: string,
    pregrav_5: number,
    pregav_12: number,
    pregrav_neg12: number,
    posgrav_5: number,
    posgrav_12: number,
    posgrav_neg12: number,
    trim_rv1: number,
    trim_rv2: number,
    trim_rv3: number,
    trim_rv4: number,
    trim_rv5: number,
    trim_rv6: number,
    trim_rv7: number,
    trim_rv8: number,
    trim_rv9: number,
    trim_rv10: number,        
    osc_5: number,
    osc_gnd: number,
    osc_12: number,
    osc_neg12: number,
    osc_vref: number,
    osc_1khz: number,
    osc_100hz: number,
     osc_10khz: number,
    dt_criacao: Date,
}
    