export default interface Config {
    id: null,
    nome: string,    
    pregrav_5_min:number,
    pregrav_5_max:number,
    pregrav_12_min:number,
    pregrav_12_max:number,
    pregrav_neg12_min:number,
    pregrav_neg12_max:number,
    posgrav_5_min:number,
    posgrav_5_max:number,
    posgrav_12_min:number,
    posgrav_12_max:number,
    posgrav_neg12_min:number,
    posgrav_neg12_max:number,
    trim_rv1: number,
    trim_rv2: number,
    trim_rv3: number,
    trim_rv4: number,
    trim_rv5: number,
    trim_rv6: number,
    trim_rv7: number,
    trim_rv8: number,
    trim_rv9: number,
    trim_rv10: number,
    osc_5_min:number,
    osc_5_max:number,
    osc_gnd_min:number,
    osc_gnd_max:number,
    osc_12_min:number,
    osc_12_max:number,
    osc_neg12_min:number,
    osc_neg12_max:number,
    osc_vref_min:number,
    osc_vref_max:number,
    osc_1khz_min:number,
    osc_1khz_max:number,
    osc_100hz_min:number,
    osc_100hz_max:number,
    osc_10khz_min:number,
    osc_10khz_max:number,
}
